### ISSUE TITLE
My first row is being duplicated

### ISSUE THREAD

**Issue by pdralston** [crunchprank/google-sheets-to-html#5] opened 2019-02-05 23:18 UTC
`query.setQuery('SELECT A, B, C, D label A "Date", B "Homework", C "Lab", D "PLC"');`

Results in my header row being duplicated. Here is a link to show the behavior:

https://jeff.cis.cabrillo.edu/~pdralston/MarcusWebsite/SitePages/Physics4C/Assignments.html

**Comment by crunchprank** [comment] 2019-02-05 23:26
My assumption is that your actual spreadsheet contains the headers that you included in the `google-sheets-html.js` file as well. The JavaScript will pull all data from the Google spreadsheet and cannot differentiate between what the Google spreadsheet considers the header of a column and the rest of the data, as that is somewhere on Google's end.

**Comment by pdralston** [comment] 2019-02-06 03:45
Hmmmm, It is strange, because when I look at the sheet from your example, it also has the headers in it, yet it does not duplicate it. I'll see if I can't find a workaround before removing it, though it sounds like I will need to.

**Comment by crunchprank** [comment] 2019-05-03 20:27
After coming back, I see that you were able to fix this from the looks of the URL you provided. Did you identify what issue you were facing that caused this? As I was never able to replicate it.

**Comment by pdralston** [comment] 2019-05-03 20:31
I was not. I just ended up removing the headers for now. I will eventually try to take a deeper look at this, but I have other items pulling my attention right now

**Comment by crunchprank** [comment] 2019-05-03 20:36
Interesting. And no problem, thanks for the update.

**Comment by crunchprank** [comment] 2020-02-17 22:43
I was unable to reproduce this issue. Closing.

**Closed as completed by crunchprank** 2020-02-17 22:43 UTC
